apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  # postgres database
  - containerPort: 31321
    hostPort: 30322
  # application
  - containerPort: 30000
    hostPort: 30102
  # Grafana
  - containerPort: 31300
    hostPort: 31302
  # vault
  - containerPort: 31400
    hostPort: 31402
  # debug port
  - containerPort: 30500
    hostPort: 30502
- role: worker
- role: worker
- role: worker
