apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  # postgres database
  - containerPort: 31321
    hostPort: 30321
  # application
  - containerPort: 30000
    hostPort: 30100
  # Grafana
  - containerPort: 31300
    hostPort: 31301
  # vault
  - containerPort: 31400
    hostPort: 31401
  # debug port
  - containerPort: 30500
    hostPort: 30501
- role: worker
- role: worker
- role: worker
