apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-cluster
  namespace: pg
  labels:
    cnpg.io/reload: ""
spec:
  description: "Postgres database cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.1
  instances: 1

  superuserSecret:
    name: pg-superuser

  managed:
    roles:
      - name: app-user
        ensure: present
        comment: user for application
        login: true
        superuser: false
        passwordSecret:
          name: app-user

  enableSuperuserAccess: true

  postgresql:
    pg_hba:
      - host all all all scram-sha-256

  bootstrap:
    initdb:
      database: aquarium_db
      owner: app-user
      secret:
        name: app-user
      postInitApplicationSQL:
        - create schema aquarium_schema authorization "app-user"
        - grant all on schema aquarium_schema to "app-user"
        - grant all on all tables in schema aquarium_schema to "app-user"
        - create user adminuser with password 'supersecret' createrole
        - grant connect on database aquarium_db to adminuser

  storage:
    size: 10Gi
    storageClass: standard

---

apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: pg
  labels:
    name: pg
spec:
  type: NodePort
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      nodePort: 31321
  selector:
    cnpg.io/cluster: db-cluster